POST http://localhost:3000/login 
Content-Type: application/json

{
    "email": "khushil@gmail.com",
    "password": "123456" 
}

###
GET https://localhost:3000/home 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtodXNoaWxAZ21haWwuY29tIiwiaWF0IjoxNjI4OTI2NDY1fQ.xuilzQGzdF0CdnRntv9FJVH0_Kc71u7dPtbSDo9Z9HI
